@baseUrl = http://localhost:5025/api/tasks

### Create a new task
POST {{baseUrl}}
Content-Type: application/json

{
  "taskName": "Sample Task 1",
  "dueDate": "2023-12-31T23:59:59",
  "description": "This is a sample task 1 description."
}

### Get a task by ID
GET {{baseUrl}}/1

### Get all tasks
GET {{baseUrl}}/tasks

### Update a task
PUT {{baseUrl}}/1
Content-Type: application/json

{
  "taskName": "Updated Task Name",
  "dueDate": "2023-12-31T23:59:59",
  "status": "IN_PROGRESS",
  "description": "Updated description."
}

### Delete a task
DELETE {{baseUrl}}/1